version: 1
disable_existing_loggers: false

# This section defines the format of your log messages
formatters:
  default:
    format: "%(levelname)s:     %(name)s - %(message)s"
  json:
    # This special '()' key points to the custom JsonFormatter class in main.py
    '()': ariadne_core.config.log.JsonFormatter

# This section defines where the logs are sent (e.g., console)
handlers:
  default:
    # The formatter used by this handler will be set dynamically in the code
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [ default ]
  propagate: false

# This section defines the loggers for different parts of the application
loggers:
  uvicorn:
    handlers: [ default ]
    level: INFO
    propagate: false
  gunicorn:
    handlers: [ default ]
    level: INFO
    propagate: false
